### ISSUE TITLE
Change app.jinja_env.globals.update() references to be a Flask context_processor

### ISSUE THREAD

**Issue by phg49389** [betheluniversity/classifieds#36]
While talking with Boston about some code he was writing in Tinker, I realized that the code I wrote a few years ago to import two functions into the templates can be enhanced.

In MyBethel, at the bottom of app/views/mybethel.py, we use Flask's built-in `@app.context_processor` to get variables and functions from Python to Jinja for rendering templates. These lines at the bottom of app/init.py can probably be converted to a context_processor as well:

```

def is_user_admin():
    return contact_is_admin(session['username'])

app_settings = get_app_settings()

app.jinja_env.globals.update(is_user_admin=is_user_admin)
app.jinja_env.globals.update(app_settings=app_settings)
```

**Comment by c-schwarze** [comment]
@bak45247 when you have a chance, you can work on this. Thanks!

**Comment by bak45247** [comment]
_References in MyBethel_

_Line 713 in MyBethel.py_: This contains the method used to create the context processor

_Line 14 in cas.html_: This contains the use of the context processor variable 'checklist_complete'

How does it work? The context processor method (labeled @app.context_processor) is run prior to rendering any templates. This give us, in the context of the template, access to all the information stored in the context processor. In cas.html, we can just use the variable for checklist_complete without any prior scoping because we just have access to it.

**Comment by bak45247** [comment]
**What needs to be done?**

- Creating this function for all of the necessary information in Classifieds init.py
- Refactoring all the previous jinja_env.globals to utilize the context_processor (will update post scanning through code and making not of use

**Comment by bak45247** [comment]
This ended up being considerably easier than I'd expected
