### ISSUE TITLE
Use Requests package

### ISSUE THREAD

**Issue by j-jasik** [betheluniversity/classifieds#39]
Use Requests package for retrieving wsapi data rather than urllib. Make sure to pull this change for both classifieds and book exchange.

**Comment by c-schwarze** [comment]
@mjweiberg28 After you finish up working on sd-signin, you can take a look at this issue. Feel free to reach out to any of the other students or any of us web devs to get you started.

In order to get a local instance, you will need a venv, config.py, and app.db. Both app.db and config.py can be grabbed from the server and then edited.

**Comment by j-jasik** [comment]
Josiah did this back in August. Closing.
